export const Products = [
    {
        id: 1,
        category: "Box's Especiales",
        title: 'Desayuno/Merienda XL',
        price: '$30.000',
        image: '/box/desayuno.png',
    },
    {
        id: 2,
        category: "Box's Especiales",
        title: 'Desayuno/Merienda',
        price: '$16.000',
        image: '/box/merienda.png',
    },
    {
        id: 3,
        category: 'Postres',
        title: 'Brownie con Frutillas (24 cm)',
        price: '$32.000',
        image: '/postres/tarta-brownie.png',
    },
    {
        id: 4,
        category: 'Catering',
        title: 'Shots Dulces',
        price: '$35.000',
        image: '/postres/shots-dulces.png',
    },
    {
        id: 5,
        category: 'Postres',
        title: 'Tarta de Frutillas (24 cm)',
        price: '$30.000',
        image: '/postres/tarta-frutillas.png',
    },
    {
        id: 6,
        category: 'Panificados',
        title: 'Pan Multicereal Artesanal',
        price: '$6.000',
        image: '/panificados/pan-cereales.png',
    },
    {
        id: 7,
        category: 'Panificados',
        title: 'Pan Blanco Artesanal',
        price: '$5.000',
        image: '/panificados/pan-blanco.png',
    },
    {
        id: 8,
        category: 'Postres',
        title: 'Lemon Pie (24 cm)',
        price: '$30.000',
        image: '/postres/lemon-pie.png',
    },
    {
        id: 9,
        category: 'Postres',
        title: 'Tarta de Ricota (24 cm)',
        price: '$30.000',
        image: '/postres/tarta-ricota.png',
    },
    {
        id: 10,
        category: 'Catering',
        title: 'Figazzas',
        price: '$20.000',
        image: '/catering/figazzas.png',
    },
    {
        id: 11,
        category: 'Catering',
        title: 'Chips',
        price: '$20.000',
        image: '/catering/chips.png',
    },
    {
        id: 12,
        category: 'Catering',
        title: 'Focaccia',
        price: '$23.000',
        image: '/catering/focaccia.png',
    },
    // {
    //     id: 13,
    //     category: 'Postres',
    //     title: '',
    //     price: '$23.000',
    //     image: '',
    // },
    // {
    //     id: 14,
    //     category: 'Postres',
    //     title: '',
    //     price: '$23.000',
    //     image: '',
    // },
    // ...
];
