export const Products = [
    {
        id: 1,
        category: 'Catering',
        title: 'Focaccias',
        price: '$25.000',
        image: '/postre.png',
    },
    {
        id: 2,
        category: 'Catering',
        title: 'Chips',
        price: '$20.000',
        image: '/brownie.png',
    },
    {
        id: 3,
        category: 'Catering',
        title: 'Figazzas',
        price: '$20.000',
        image: '/brownie.png',
    },
    {
        id: 4,
        category: 'Catering',
        title: 'Shots Dulces',
        price: '$35.000',
        image: '/postre.png',
    },
    {
        id: 5,
        category: 'Cookies',
        title: 'Caja de Cookies Variadas (6u)',
        price: '$18.000',
        image: '/postre.png',
    },
    {
        id: 6,
        category: 'Panes',
        title: 'Pan Integral Artesanal',
        price: '$8.500',
        image: '/postre.png',
    },
    {
        id: 7,
        category: 'Cupcakes',
        title: 'Caja de Cupcakes (6u)',
        price: '$24.000',
        image: '/postre.png',
    },
    {
        id: 8,
        category: 'Muffins',
        title: 'Caja de Muffins (6u)',
        price: '$20.000',
        image: '/postre.png',
    },
    {
        id: 9,
        category: 'Cheesecakes',
        title: 'Cheesecake Clásico',
        price: '$27.500',
        image: '/postre.png',
    },
    {
        id: 10,
        category: 'Tartas',
        title: 'Tarta de Frutas',
        price: '$23.000',
        image: '/postre.png',
    },
    {
        id: 11,
        category: 'Desayunos',
        title: 'Desayuno Sorpresa',
        price: '$75.000',
        image: '/postre.png',
    },
    {
        id: 12,
        category: 'Panificados',
        title: 'Baguette Artesanal',
        price: '$9.000',
        image: '/postre.png',
    },
    // ...
];
