export const ProductSellers = [
    {
        id: 1,
        category: 'Postres',
        title: 'Tarta de Frutillas (24 cm)',
        price: '$30.000',
        image: '/postres/tarta-frutillas.png',
    },
    {
        id: 2,
        category: 'Postres',
        title: 'Lemon pie (24 cm)',
        price: '$30.000',
        image: '/postres/lemon-pie.png',
    },
    {
        id: 3,
        category: 'Postres',
        title: 'Brownie con Frutillas (24 cm)',
        price: '$32.000',
        image: '/postres/tarta-brownie.png',
    },
    {
        id: 4,
        category: 'Postres',
        title: 'Tarta de Ricota (24 cm)',
        price: '$30.000',
        image: '/postres/tarta-ricota.png',
    },
    {
        id: 5,
        category: "Box's Especiales",
        title: 'Desayuno/Merienda',
        price: '$16.000',
        image: '/box/merienda.png',
    },
    {
        id: 6,
        category: "Box's Especiales",
        title: 'Desayuno/Merienda XL',
        price: '$30.000',
        image: '/box/desayuno.png',
    },
    {
        id: 7,
        category: 'Catering',
        title: 'Figazzas x12u',
        price: '$20.000',
        image: '/catering/figazzas.png',
    },
    {
        id: 8,
        category: 'Catering',
        title: 'Chips x12u',
        price: '$20.000',
        image: '/catering/chips.png',
    },
];
