export const Products = [
    {
        id: 1,
        category: "Box's Especiales",
        title: 'Desayuno/Merienda XL',
        price: '$30.000',
        image: '/box/desayuno.png',
    },
    {
        id: 2,
        category: "Box's Especiales",
        title: 'Desayuno/Merienda',
        price: '$16.000',
        image: '/box/merienda.png',
    },
    {
        id: 3,
        category: 'Postres',
        title: 'Brownie con Frutillas (24 cm)',
        price: '$40.000',
        image: '/postres/tarta-brownie.png',
    },
    {
        id: 4,
        category: 'Catering',
        title: 'Shots Dulces x12u',
        price: '$35.000',
        image: '/catering/shots-dulces.png',
    },
    {
        id: 5,
        category: 'Postres',
        title: 'Tarta de Frutillas (24 cm)',
        price: '$30.000',
        image: '/postres/tarta-frutillas.png',
    },
    {
        id: 6,
        category: 'Panificados',
        title: 'Pan Multicereal Artesanal',
        price: '$6.000',
        image: '/panificados/pan-cereales.png',
    },
    {
        id: 7,
        category: 'Panificados',
        title: 'Pan Blanco Artesanal',
        price: '$5.000',
        image: '/panificados/pan-blanco.png',
    },
    {
        id: 8,
        category: 'Postres',
        title: 'Lemon Pie (24 cm)',
        price: '$30.000',
        image: '/postres/lemon-pie.png',
    },
    {
        id: 9,
        category: 'Postres',
        title: 'Tarta de Ricota (24 cm)',
        price: '$30.000',
        image: '/postres/tarta-ricota.png',
    },
    {
        id: 10,
        category: 'Catering',
        title: 'Figazzas x12u',
        price: '$20.000',
        image: '/catering/figazzas.png',
    },
    {
        id: 11,
        category: 'Catering',
        title: 'Chips x12',
        price: '$20.000',
        image: '/catering/chips.png',
    },
    {
        id: 12,
        category: 'Catering',
        title: 'Focaccia x12u',
        price: '$23.000',
        image: '/catering/focaccia.png',
    },
    {
        id: 13,
        category: 'Postres',
        title: 'Brownie con Merengue (24 cm)',
        price: '$35.000',
        image: '/postres/brownie-merengue.png',
    },
    {
        id: 14,
        category: 'Postres',
        title: 'Alfajores de Maicena x12u',
        price: '$10.500',
        image: '/postres/alfajores-maicena.png',
    },
    {
        id: 15,
        category: 'Postres',
        title: 'Alfajores de Chocolate x12u',
        price: '$10.500',
        image: '/postres/alfajores-chocolate.png',
    },
    {
        id: 16,
        category: 'Panificados',
        title: 'Prepizza (Tomate) x4u',
        price: '$3.000',
        image: '/panificados/prepizza-tomate.png',
    },
    {
        id: 17,
        category: 'Panificados',
        title: 'Prepizza (Cebolla) x1u',
        price: '$3.500',
        image: '/panificados/prepizza-cebolla.png',
    },
    {
        id: 18,
        category: 'Panificados',
        title: 'Prepizzetas (Tomate) x12u',
        price: '$4.000',
        image: '/panificados/prepizzetas-tomate.png',
    },
    {
        id: 19,
        category: 'Panificados',
        title: 'Prepizzetas (Cebolla) x12u',
        price: '$4.500',
        image: '/panificados/prepizzetas-cebolla.png',
    },
    {
        id: 20,
        category: 'Panificados',
        title: 'Trenza de aceitunas y queso',
        price: '$9.000',
        image: '/panificados/trenza-aceitunas.png',
    },
    {
        id: 21,
        category: 'Panificados',
        title: 'Medialunas x12u',
        price: '$13.500',
        image: '/panificados/medialunas.png',
    },
    // ...
];
