import { Lato, Montserrat, Open_Sans, Poppins } from "next/font/google";
import Navbar from "./components/Navbar";
import type { Metadata } from "next";
import "./globals.css";
// app/layout.tsx
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import Footer from "./components/Footer";

config.autoAddCss = false;

export const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});

export const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
  display: "swap",
});

export const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-open-sans",
  display: "swap",
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Oliva's Deli",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`
        ${lato.variable}
        ${montserrat.variable}
        ${openSans.variable}
        ${poppins.variable}
      `}
    >
      <body
        className="min-h-screen bg-linear-to-br from-[#f6eef5] via-white to-[#ede3ec]"
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
